name: CI/CD Pipeline with PM2 3 package

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Setup SSH for EC2
      - name: Setup SSH for EC2
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 6: Deploy to EC2 using PM2
      - name: Deploy app with PM2
        uses: victorargento/pm2-deployment@main
        with:
          remote-path: "/home/${{ secrets.EC2_USERNAME }}/app"
          host: ${{ secrets.EC2_URL }}
          username: ${{ secrets.EC2_USERNAME }}
          port: 22  # Standard SSH port, change if necessary
          pm2-id: "app"  # Name of your PM2 app
          build: true

      # Step 8: Finalize PM2 and Nginx setup
      - name: Finalize deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << EOF
              # Save PM2 process list and set to start on boot
              /usr/local/bin/pm2 save
              sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER

              # Install Nginx if not present
              if ! command -v nginx &> /dev/null; then
                sudo apt-get install -y nginx
              fi

              # Create Nginx configuration
              sudo tee /etc/nginx/sites-available/default > /dev/null << EOL
              server {
                  listen 80;
                  server_name ${{ secrets.EC2_URL }};
              
                  location / {
                      proxy_pass http://localhost:$PORT;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade \$http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_set_header Host \$host;
                      proxy_cache_bypass \$http_upgrade;
                  }
              }
              EOL

              # Restart Nginx
              sudo systemctl restart nginx

              # Clean up
              npm cache clean --force
              sudo apt-get clean
              sudo rm -rf /var/lib/apt/lists/*

              echo "Cleaning up log files..."
              sudo find /var/log/ -type f -name "*.log" -exec truncate -s 0 {} +

              echo "Checking disk usage after cleanup..."
              df -h
          EOF

      # Step 9: Verify PM2 processes
      - name: Verify PM2 process
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} \
          "/usr/local/bin/pm2 list"
